x-supernode: &sn
  image: flwr/supernode:1.39.0
  environment: &env
    FLWR_MODEL_API_KEY: ${FLWR_MODEL_API_KEY:?Set FLWR_MODEL_API_KEY before running docker compose}

services:
  supernode-nepal:
    <<: *sn
    command:
      - --superlink=fleet-supergrid.flower.ai:443
      - --auth-supernode-private-key=/keys/supernode-0
      - --allow-runtime-dependency-installation
    environment:
      <<: *env
      FLWR_FILESYSTEM_ALLOWED_DIRS: /data/supernode-nepal
    volumes:
      - ./keys:/keys:ro
      - ./data/supernode-nepal:/data/supernode-nepal

  supernode-india:
    <<: *sn
    command:
      - --superlink=fleet-supergrid.flower.ai:443
      - --auth-supernode-private-key=/keys/supernode-1
      - --allow-runtime-dependency-installation
    environment:
      <<: *env
      FLWR_FILESYSTEM_ALLOWED_DIRS: /data/supernode-india
    volumes:
      - ./keys:/keys:ro
      - ./data/supernode-india:/data/supernode-india

  supernode-china:
    <<: *sn
    command:
      - --superlink=fleet-supergrid.flower.ai:443
      - --auth-supernode-private-key=/keys/supernode-2
      - --allow-runtime-dependency-installation
    environment:
      <<: *env
      FLWR_FILESYSTEM_ALLOWED_DIRS: /data/supernode-china
    volumes:
      - ./keys:/keys:ro
      - ./data/supernode-china:/data/supernode-china

  supernode-bhutan:
    <<: *sn
    command:
      - --superlink=fleet-supergrid.flower.ai:443
      - --auth-supernode-private-key=/keys/supernode-3
      - --allow-runtime-dependency-installation
    environment:
      <<: *env
      FLWR_FILESYSTEM_ALLOWED_DIRS: /data/supernode-bhutan
    volumes:
      - ./keys:/keys:ro
      - ./data/supernode-bhutan:/data/supernode-bhutan

  supernode-myanmar:
    <<: *sn
    command:
      - --superlink=fleet-supergrid.flower.ai:443
      - --auth-supernode-private-key=/keys/supernode-4
      - --allow-runtime-dependency-installation
    environment:
      <<: *env
      FLWR_FILESYSTEM_ALLOWED_DIRS: /data/supernode-myanmar
    volumes:
      - ./keys:/keys:ro
      - ./data/supernode-myanmar:/data/supernode-myanmar
